version: 3.0.{build}

environment:
  api_key:
    #secure: Mcd+DRZEtMGvt5JtzC8a3VeN2jG7PNSpsfA8dM4nb37X78TJa1nW81pdpx0V2n6N
    secure: 5a8Gq7E2Zux0sVrxSbw+9VKECHmk3NnvaBv1fc+g7ZAitrZ0oAGwBD3baOe/rPqG

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
  
test: off

deploy:
- provider: NuGet
  api_key:
    #secure: Mcd+DRZEtMGvt5JtzC8a3VeN2jG7PNSpsfA8dM4nb37X78TJa1nW81pdpx0V2n6N
    secure: 5a8Gq7E2Zux0sVrxSbw+9VKECHmk3NnvaBv1fc+g7ZAitrZ0oAGwBD3baOe/rPqG
  skip_symbols: true

#deploy_script:
#  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
#  - nuget.exe setApiKey %api_key% -source https://www.nuget.org
#  - ps: ($artifacts.values | Where-Object { $_.path -like '*.nupkg' }) | foreach-object {nuget.exe push $_.path -Source https://www.nuget.org/api/v2/package; if ($lastexitcode -ne 0) {throw}}
