version: 3.1.{build}

#environment:
#  APPVEYOR_USE_NUGET_EXE_FOR_PUBLISHING: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
  
test: off

deploy:
- provider: NuGet
  api_key:
      secure: IOY9mo3EZvawI7BnY5GRbjWomorpN8E9W9FO5u30KSqTGrnr3QdzRXBEmIQYEdEf
  
