version: 3.1.{build}

environment:
  APPVEYOR_USE_NUGET_EXE_FOR_PUBLISHING: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  include_nuget_references: true
  verbosity: minimal
  
test: off

#time to attach debugger
#init:
#- ps: sleep 20

#secure: 5a8Gq7E2Zux0sVrxSbw+9VKECHmk3NnvaBv1fc+g7ZAitrZ0oAGwBD3baOe/rPqG

deploy:
- provider: NuGet
  api_key:
      secure: 9mTcY4UWSOlDTul4r8SxFWI1In275/q8RygA/DzJU/H/PNzjExM0+QohtwuIL3Lt
  #skip_symbols: true

#deploy_script:
#  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe  
#  - ps: ($artifacts.values | Where-Object {($_.path -like '*.nupkg') -and  !($_.path -like '*.symbols.nupkg')}) | foreach-object {nuget.exe push $_.path -Source https://www.nuget.org/api/v2/package -ApiKey $env:api_key;}
